spring:
  datasource:
    password: aaFurnitures
    username: aaFurnitures
    url: jdbc:mysql://localhost:3306/aaFurnitures
  
    
logging:
  level:
    root: warn
    '[com.promineotechfinals]': debug